### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#1]

**Comment by karpiu** [comment]
Anyone working on it? If no, I will do it.

**Comment by tarebyte** [comment]
@karpiu not as far as I know, go for it 👍

**Comment by karpiu** [comment]
`will_paginate` gem will do?

**Comment by tarebyte** [comment]
@karpiu I feel like https://github.com/amatsuda/kaminari is better maintained, but I could be wrong.

**Comment by karpiu** [comment]
@tarebyte I can work with whichever you prefer. So `kaminari` it is :shipit:

**Comment by andrew** [comment]
You can generate some nice styles with: `rails g kaminari:views bootstrap3`

**Comment by karpiu** [comment]
@andrew great tip. Thanks!
