### ISSUE TITLE
Sidebar filter order

### ISSUE THREAD

**Issue by briannelson** [andrew/octobox#114]
Presumably, Inbox, Archive, and Starred are the most important filters. We should move these to the top.

![octobox](https://cloud.githubusercontent.com/assets/29120/21406334/0f9c7284-c799-11e6-8c95-2c2187512650.png)

**Comment by tarebyte** [comment]
@briannelson I was just thinking that as well, feel free to open a PR!

**Comment by briannelson** [comment]
I'll try to work on a better sidebar display tonight. Too many lines for my taste :) No offense @andrew

**Comment by andrew** [comment]
I'm immune to offense when it comes to design work I did on Sunday night!

**Comment by knolleary** [comment]
Just raised PR #115 related to filters.
Whilst putting that together, I noticed that the filter links in the sidebar are slightly inconsistent in their behaviour - for example, clicking a `type` filter also clears any current `reason` filter. I didn't touch it under #115 as I didn't want to overload it.

@briannelson - if you're delving in there, could you look at that as well?

**Comment by briannelson** [comment]
I'm actually seeing something that I think is related, but good point @knolleary. Because of the way filters get applied, it's possible to have more than one active at a time, currently. This is more of a UX question @andrew / @tarebyte. 

<img width="411" alt="octobox" src="https://cloud.githubusercontent.com/assets/29120/21407217/66b09402-c79d-11e6-9fa2-e58c5ca9023f.png">

If I'm reading it correctly, there are 2 buckets (Inbox, Archive), and within those you can filter by all the rest. (Starred seems like it should be its own bucket, fwiw, independent of Inbox and Archive). Anyways, not sure a good direction here, just wanted to get it down for now.

**Comment by tarebyte** [comment]
@briannelson yes that is correct, `Starred` is a kind of filter of I don't think it belongs in the same section as the Archive and the Inbox.

**Comment by briannelson** [comment]
So, to be clear, Archive Starred and Inbox Starred are two different lists, potentially?

**Comment by tarebyte** [comment]
> So, to be clear, Archive Starred and Inbox Starred are two different lists, potentially?

They are two different lists correct. The inbox removes the archived parameter from the URL.

**Comment by briannelson** [comment]
That seems like an anti-pattern to me. 
i.e. if I star something, it's important to me whether it's archived it's not. 

My suggestion is to make starred independent of Inbox and Archive so you click it and see ALL your starred messages. The checkbox would be checked for those that are archived and unchecked for those that aren't.

Is there a use-case I'm missing here for why two separate lists are important?

**Comment by tarebyte** [comment]
> Is there a use-case I'm missing here for why two separate lists are important?

Nope I think it's just the way it is ¯\\_(ツ)_/¯

> That seems like an anti-pattern to me.
> i.e. if I star something, it's important to me whether it's archived it's not.
> 
> My suggestion is to make starred independent of Inbox and Archive so you click it and see ALL your starred messages. The checkbox would be checked for those that are archived and unchecked for those that aren't.

I'd be cool with that, I'll throw up a PR and see what you think.

**Comment by andrew** [comment]
Feel free to change it to what makes most sense, it was all hacked together initially with little thought to the UX

**Comment by briannelson** [comment]
What do you think of:

<img width="270" alt="octobox" src="https://cloud.githubusercontent.com/assets/29120/21411024/3b08078e-c7b3-11e6-9403-3f6e85cf9975.png">

**Comment by andrew** [comment]
LGTM 👍
