### ISSUE TITLE
Docker image(s) for those who don't want to run all of the deps locally

### ISSUE THREAD

**Issue by atuttle** [andrew/octobox#12]
It would be nice if there were a docker container I could spin up, instead of making sure I have the appropriate versions of ruby/postgres/etc and configuring them together.

FWIW I'm going to try my hand at putting one together. If I get anywhere I'll happily contribute it back.

**Comment by bfred-it** [comment]
There's a Deploy to Heroku button that works fairly well, if that's enough.

**Comment by andrew** [comment]
👍

**Comment by andrew** [comment]
@atuttle there's a pull request open to add some config for a docker box now, can you double check it for me? https://github.com/andrew/github-inbox/pull/35

**Comment by atuttle** [comment]
I'm looking at it now. Seems to be working. 👍🏻
