### ISSUE TITLE
Make it look more like Github?

### ISSUE THREAD

**Issue by briannelson** [andrew/octobox#121]
Should Octobox aim to "fit in" with Github's styling so that it feels like less of a context switch?

<img width="1440" alt="octobox" src="https://cloud.githubusercontent.com/assets/29120/21416534/a0bd7a5e-c7e1-11e6-8b96-b2bd50df2213.png">

**Comment by andrew** [comment]
Looks nice! I still prefer the envelope icon to the octocat head, I wonder if we could combine them?

**Comment by briannelson** [comment]
I'll work on that a bit :)

**Comment by briannelson** [comment]
Is this paresable?

<img width="101" alt="untitled" src="https://cloud.githubusercontent.com/assets/29120/21426381/a86d3f74-c81c-11e6-8be2-6a03e4c3d456.png"> <img width="57" alt="untitled" src="https://cloud.githubusercontent.com/assets/29120/21426392/b27f3936-c81c-11e6-96db-a38477769837.png"> <img width="35" alt="untitled" src="https://cloud.githubusercontent.com/assets/29120/21426400/b9fa00f6-c81c-11e6-9aa0-c5b5cc478b20.png">

**Comment by andrew** [comment]
Very cute!
