### ISSUE TITLE
Views license?

### ISSUE THREAD

**Issue by m1guelpf** [andrew/octobox#122]
Hi!
I am doing a Laravel project to learn to use laravel and the Github API, and it's processing the notifications, and returning specifics pages depending of the type of notification. I'd like to know if I can use this project's views. I'm going to license my project under the MIT license and I'd give credits.
Repo: https://github.com/m1guelpf/github

**Comment by andrew** [comment]
You'll have to license your code as AGPL if you are going to use any code from this project

**Comment by m1guelpf** [comment]
@andrew So if I use http://choosealicense.com/licenses/agpl-3.0/# , I don't need to do anything more and I can use them!

**Comment by andrew** [comment]
Yep 👍

**Comment by m1guelpf** [comment]
Thank you!
