### ISSUE TITLE
Better notification syncing with "If-Modified-Since" header

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#125]
If a notification has been marked as read on GitHub, but hasn't changed state and you don't have any new notifications then the current syncing method won't download the change in unread state.

That's because we pass `user.last_synced_at` as the `:since` option when downloading notifications, which is a little bit annoying as there's no way for octobox to mark the notifications as read if there's no new activity on GitHub.

Fortunately there's another way to get round this listed in the Notifications API docs: https://developer.github.com/v3/activity/notifications/

> Notifications are optimized for polling with the "Last-Modified" header. If there are no new notifications, you will see a "304 Not Modified" response, leaving your current rate limit untouched. There is an "X-Poll-Interval" header that specifies how often (in seconds) you are allowed to poll. In times of high server load, the time may increase. Please obey the header.

```
# Add authentication to your requests
curl -I https://api.github.com/notifications
HTTP/1.1 200 OK
Last-Modified: Thu, 25 Oct 2012 15:16:27 GMT
X-Poll-Interval: 60

# Pass the Last-Modified header exactly
curl -I https://api.github.com/notifications
   -H "If-Modified-Since: Thu, 25 Oct 2012 15:16:27 GMT"
HTTP/1.1 304 Not Modified
X-Poll-Interval: 60
```

I don't think that Octokit supports this out of the box so we have two options:

1. Use some custom middleware with octokit like I do in Libraries.io with caching and 304 support: https://github.com/librariesio/libraries.io/blob/master/config/initializers/octokit.rb

2. Don't use Octokit to download the notifications and instead do a plain request including the `If-Modified-Since` header with the value of `user.last_synced_at` and always send a `since` value of `1.month.ago.iso8601`

**Comment by tarebyte** [comment]
> Use some custom middleware with octokit like I do in Libraries.io with caching and 304 support: https://github.com/librariesio/libraries.io/blob/master/config/initializers/octokit.rb

I'm very much in favor of using Octokit and adding caching.

**Comment by tarebyte** [comment]
@andrew do we want to add memcached for a caching layer?

**Comment by andrew** [comment]
@tarebyte yeah memcached sounds good to me, and if we use `Rails.cache` everywhere it allows other users to swap out the cache mechanism if they wish.

**Comment by andrew** [comment]
Just shipped to heroku, had to make a couple tweaks and disable the connection pool option as it was exploding 🚢
