### ISSUE TITLE
'Release' types in sidebar missing icon

### ISSUE THREAD

**Issue by knolleary** [andrew/octobox#129]
The Release type in the sidebar has no icon, so appears misaligned:

<img width="139" alt="cursor_and_octobox" src="https://cloud.githubusercontent.com/assets/51083/21432256/87e6e6f6-c862-11e6-8583-707de828377a.png">

Either need to add an icon (not sure if there is one...) or pad it out to keep things lined up.

**Comment by briannelson** [comment]
Use the tag icon, maybe?

<img width="140" alt="kickserv_kickserv__the_main_kickserv_app" src="https://cloud.githubusercontent.com/assets/29120/21432832/440bc338-c83b-11e6-9c99-a63b6cb22a8c.png">

**Comment by knolleary** [comment]
Ah yes, that'll work. The PR I've stuck in will ensure any types that don't have an icon defined will still lined up. Will add in the tag icon for release now.

**Comment by andrew** [comment]
🚢
