### ISSUE TITLE
GitHub Enterprise config

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#14]
In theory this should "just work" with an enterprise install if we make the domain configurable in the Notification class

**Comment by boffbowsh** [comment]
I have access to an Enterprise instance so I'll try and find time to do the work on this 👍 . Are you envisaging separate installs of Inbox per GH instance?

**Comment by andrew** [comment]
@boffbowsh yeah definitely, let people run it internally for their own usage be it Github.com or Enterprise
