### ISSUE TITLE
More friendly on mobile

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#15]
Haven't checked what the site looks like on mobile but I'd bet it's not great 😬

**Comment by briannelson** [comment]
I'll take a crack at this @andrew. Before I start, any objection to using Octicons in lieu of Font Awesome? Might play a bit nicer with Github itself.

**Comment by briannelson** [comment]
@andrew thoughts on this direction? I've sort of overstepped the scope of this issue, but will push up a PR soon that covers mobile betterness as well :)

<img width="1206" alt="octobox" src="https://cloud.githubusercontent.com/assets/29120/21352518/d115ce20-c68f-11e6-96f5-517d2c2025c9.png">

**Comment by andrew** [comment]
@briannelson looking nice!

**Comment by tarebyte** [comment]
Done ✨
