### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by boffbowsh** [andrew/octobox#20]
a la Gmail. A lot of notifications are generated across my organisation. I generally skim the subjects and mass-archive them off when dealing with them via Gmail. This workflow would be really useful here.

Mainly, lots of j,x,j,x,j,x,y.

**Comment by andrew** [comment]
👍

**Comment by karpiu** [comment]
Is someone on it? If no, I will do it.

**Comment by andrew** [comment]
Go for it!

**Comment by boffbowsh** [comment]
Please do!

**Comment by andrew** [comment]
Fixed by @karpiu in https://github.com/andrew/octobox/issues/36
