### ISSUE TITLE
Oauth Login

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#3]
Currently you have to make a personal access token and run the app yourself, we can [omniauth-github](https://github.com/intridea/omniauth-github) to enable people to login via a hosted version without having to run the app themselves.

**Comment by ckuhn203** [comment]
I'm happy to see this issue already opened. My very first thought was that I'd like to deploy to my VPS.

**Comment by tarebyte** [comment]
@andrew I've got a branch in the works.

PR coming soon!

**Comment by andrew** [comment]
@tarebyte 👏
