### ISSUE TITLE
Is it possible to show the issue/pull request status?

### ISSUE THREAD

**Issue by ben-eb** [andrew/octobox#45]
This is a great project, thanks!

I was just wondering if it's possible to show if an issue is open/closed, or if a pull request is open/merged/closed? This would be really nice to see at a glance if issues would need further action.

**Comment by andrew** [comment]
Yep, planned here: https://github.com/andrew/octobox/issues/4

**Comment by ben-eb** [comment]
Ah brilliant, I'll track that issue instead. Thanks! 👍
