### ISSUE TITLE
UI looks funky after archiving everything

### ISSUE THREAD

**Issue by jdm** [andrew/octobox#59]
<img width="1386" alt="screen shot 2016-12-19 at 6 18 49 pm" src="https://cloud.githubusercontent.com/assets/27658/21332610/a1c7dd84-c617-11e6-8c88-df565b39ba16.png">

**Comment by karpiu** [comment]
Don't know about "funky" but I noticed a bug in your screenshot that is probably my fault: the little blue vertical line for navigating notifications. It should not be visible if the list is empty. I will fix it.

**Comment by tarebyte** [comment]
Closed by #66

**Comment by karpiu** [comment]
@tarebyte Not sure if you should close this one. @jdm have not explained yet what "funky" means

**Comment by jdm** [comment]
It was the blue line, but also the big white space on the top left above the Archive link.

**Comment by andrew** [comment]
Blue line is fixed, big white space on the left needs to be squashed as there are empty tables there padding it out

**Comment by karpiu** [comment]
@andrew Ok. I will fix this.
