### ISSUE TITLE
Cursor position resets after archiving

### ISSUE THREAD

**Issue by jdm** [andrew/octobox#70]
If I leave several notifications to look at later and want to archive a bunch of ones below them, this means I have to scroll down past them every time. This feels inefficient to me!

**Comment by andrew** [comment]
We're using turbolinks so each archive is actually a page refresh on the sly!

I'm sure there's a way we can have it remember it across page refreshes.

**Comment by jdm** [comment]
I will say that on a pokey connection the page refresh is not particularly sly ;)

**Comment by andrew** [comment]
Not sly, but it does mean a lot less javascript to worry about

**Comment by karpiu** [comment]
I will do it.
