### ISSUE TITLE
Opening notifications overrides the previous opened notification

### ISSUE THREAD

**Issue by jdm** [andrew/octobox#71]
If I press enter on three notifications in a row, only a single tab is opened and it shows the content of the last notification that I opened. I would expect this to open three separate tabs, instead.

**Comment by karpiu** [comment]
The same happens when you simply click on three notifications with a mouse. Tested on Chrome and Firefox. Weird bug.

**Comment by andrew** [comment]
I think this is the issue: http://stackoverflow.com/questions/7952847/blank-links-opens-in-the-same-window-why-and-how-to-fix-it

**Comment by karpiu** [comment]
changing `target='blank'` to `target='_blank'` fixes the bug for me. Someone can double-check this? @andrew @jdm

**Comment by andrew** [comment]
@karpiu looks like it 👍

**Comment by jdm** [comment]
Yes, _blank is a special name in web browsers, otherwise it uses a named target window.

**Comment by karpiu** [comment]
Should I make the PR?

**Comment by andrew** [comment]
@karpiu yes please!
