### ISSUE TITLE
Trouble with heroko

### ISSUE THREAD

**Issue by plaindocs** [andrew/octobox#73]
So I'm trying to deploy to Heroku: 

I've retro fitted the URLs into the GH case they matter, added an Oath client/secret. 

When I get the Sign in with GitHub button, I'm transferred to the heroku dash not the app. Do I need any permission other than notifications?

Or is there something obvious I'm missing?

**Comment by tarebyte** [comment]
@plaindocs to make sure I understand you're trying to use Octobox for GItHub Enterprise?

If that's the case I just opened up a Pull Request (#72) which may be of some assistance to you.

**Comment by plaindocs** [comment]
Cheers for the quick response @tarebyte . No, not enterprise - just a mix of private and public repos on GH.

**Comment by tarebyte** [comment]
@plaindocs so on top of setting your Client ID and secret you'll also have to configure your token scope.

If you want private repos you need to update the `GITHUB_SCOPES` environment variable to be `repo,notifications`.

**Comment by andrew** [comment]
@tarebyte we should add a note about that in the readme

**Comment by plaindocs** [comment]
hmmm, so I needed to fix up the callback URL, which isn't mentioned in the README at all.

After getting that right, I can authenticate, but see no notifcations. Should I be able to see the public ones if I don't update the scope? Which I did.

**Comment by plaindocs** [comment]
I can update the README

**Comment by tarebyte** [comment]
@plaindocs if you press the sync button up at the top does it load your notifications for you?

**Comment by tarebyte** [comment]
> hmmm, so I needed to fix up the callback URL, which isn't mentioned in the README at all.

What about the callback url did you have to change?

**Comment by plaindocs** [comment]
In the GH I needed to add the `Heroku-app.heroku.com/auth/github/callback` (going off the image further down in the README)

**Comment by plaindocs** [comment]
No joy on sync.

**Comment by tarebyte** [comment]
In the Octobox application or on GitHub?

**Comment by andrew** [comment]
@plaindocs yeah it should be herokuappname.herokuapp.com/auth/github/callback with the same http/https protocol as you are accessing the site from.

**Comment by tarebyte** [comment]
@plaindocs I'm closing this, but feel free to ping us if you have other issues.

**Comment by plaindocs** [comment]
Thanks for all the feedback. I get either this or the hosted thing to work, so don't really know what is up. I was going up update the readme, but quite reluctant to do that without getting things to work.

**Comment by andrew** [comment]
@plaindocs have you tried the Docker approach in the readme? I used it over the holidays and it worked well for me

**Comment by basejumpa** [comment]
The correct environment variable is (now) `GITHUB_SCOPE`, so w/o an `S`, see
 
https://github.com/octobox/octobox/search?q=GITHUB_SCOPE&unscoped_q=GITHUB_SCOPE
