### ISSUE TITLE
Archive all should be context specific

### ISSUE THREAD

**Issue by M-Zuber** [andrew/octobox#75]
If I am viewing all issues from a specific repository, I want to clear them all in one click.
Archive all hits everything in all my notifications.

Is there currently a way to do what I want?

**Comment by tarebyte** [comment]
Not right now, the archive all action would have to take the current parameters into context to be able to figure out what constitutes all.

**Comment by oyeanuj** [comment]
I created another issue for that, only to close it after finding this. Big +1 for this issue.

Here is the comment from there -

---
Hi @andrew, this is a super useful tool and I am glad you put it out there!

I ran into one major bummer though - At the top of every list, is a button called 'Archive All'. I clicked on it with the assumption that it would archive all of the notifications in that list. Unfortunately, it seemed to archive all 500 notifications.

Moreover, there wasn't an undo functionality for that either :(

So, I wonder if you would consider -

Scoping that 'Archive All' to that list itself? A global 'Archive All' might make more sense somewhere in the left side navigation, for example?
Providing an undo option? I imagine, this would be far more tricky but just wanted to put it out there.
Thank you for providing this tool!

---

**Comment by knolleary** [comment]
I think there's a related feature here where a user may want to select multiple notifications and archive just those. I got caught out as I assumed the checkboxes where actually checkboxes I archived a number of notifications before I realised they are actually buttons.

This would suggest having an action that you can provide a list of notifications to archive would satisfy both the context-sensitive archive all, and the archive-selected option.

**Comment by andrew** [comment]
@knolleary agreed, related issue here: https://github.com/andrew/octobox/issues/60

**Comment by andrew** [comment]
Also related: https://github.com/andrew/octobox/issues/68

**Comment by andrew** [comment]
As I said in #60, we should make the checkboxes behave more like gmail, select one or many and perform an action on those notifications
