### ISSUE TITLE
Have list of "MAINTAINED" repository

### ISSUE THREAD

**Issue by Raffo** [andrew/octobox#78]
I would love to use this tool to have a visualization of all the notifications for repos I am a maintainer of, namely by looking at the "MAINTAINERS.md" file in the repo. I am willing to do the changes by myself if we agree that you are interested in this features, with some guidance given that I'm not good at rails.

**Comment by andrew** [comment]
@Raffo I think this is outside of the scope of this project, it currently uses the GitHub watch/not watch/mute functionality to determine which notifications come in which will work for 99% of use cases as it's exactly the same as on github.com

**Comment by Raffo** [comment]
Yeah, I saw the code and I get it, thanks anyways, please ping me in case you reconsider something similar.
