### ISSUE TITLE
updated_at clashes

### ISSUE THREAD

**Issue by andrew** [andrew/octobox#88]
When you star a notification rails automatically updates `updated_at`, but we also store the `updated_at` from the github api response and in theory sort by that.

It ends up putting the most recently starred/archived notifications at the top of the list, very confusing. We should either stop rails updating the timestamp on those saves or use a different field to store the data from GH

**Comment by nu11p01n73R** [comment]
1. Can't we use `update_column` instead of `update_attribute` to prevent updating the `updated_at`?
2. Shouldn't we do the same for un-archiving of notifications as well. Because now the if you remove a notification from archive it goes back to the top of the list.

**Comment by andrew** [comment]
@nu11p01n73R just did exactly that: https://github.com/andrew/octobox/commit/c87aea61b588565564da3431cb88742535cc0013

Great minds think alike!
