### ISSUE TITLE
Homepage has two different colors

### ISSUE THREAD

**Issue by tarebyte** [andrew/octobox#94]
Looks like it's related to the changes from #81

![screen shot 2016-12-20 at 21 09 06](https://cloud.githubusercontent.com/assets/564113/21374991/952aae8a-c6f8-11e6-9201-14b7bad8a6ee.png)

/cc @briannelson

**Comment by briannelson** [comment]
Oh, ha. I saw that and thought it was a stylistic choice you made, not remembering I had changed the background color myself.

#whoops
