### ISSUE TITLE
keyboard shortcuts `r` or `.` failed

### ISSUE THREAD

**Issue by AntSworD** [andrew/octobox#97]
I was display by heroku
When i press `r` or `.`, href to `/sync`, throw a error msg.
![image](https://cloud.githubusercontent.com/assets/2549087/21383127/20fe7c38-c79f-11e6-92a0-578de9bdaf93.png)

**Comment by karpiu** [comment]
yes. in development: `No route matches [GET] "/sync"`. I will fix it now.
